resolver: lts-12.19
packages:
- .
- pkgs/monad-freshid
- pkgs/jhc-solvers
- pkgs/jhc-logger
- pkgs/language-grin-jhc


extra-deps:
- github: seagull-kamome/containers-missing
  commit: 01b70448cef96bb238a0c419966da9b35634acb3

