name:                language-grin-jhc
version:             0.8.2.0
github:              "seagull-kamome/jhc"
license:             BSD3
author:              "Hattori, Hiroki"
maintainer:          "seagull.kamome@gmail.com"
copyright:           "Copyright (C) 2018 Hattori, Hiroki. All Rights Reserved."
synopsis:            GRIN languages AST, Parser, PrettyPrinter ...
category:            Language
description:         Please see the README on GitHub at <https://github.com/seagull-kamome/jhc#readme>


library:
  source-dirs: src
  ghc-options:
    - -Wall
  default-extensions:
    - CPP
    - BangPatterns
    - GADTs
    - StandaloneDeriving
    - RankNTypes
    - DataKinds
    - KindSignatures
    - RecordWildCards
    - NamedFieldPuns
    - OverloadedStrings
    - FlexibleInstances
    - FunctionalDependencies
    - FlexibleContexts
    - LambdaCase
    - MultiWayIf
    - ExistentialQuantification
    - GeneralizedNewtypeDeriving
    - TypeFamilies
    - PartialTypeSignatures
    - ScopedTypeVariables
    - ParallelListComp
  dependencies:
    - base >= 4.7 && < 5
    - text
    - mtl
    - transformers
    - containers
    - containers-missing
    - ansi-wl-pprint
    - jhc-logger
    - jhc-solvers == 0.8.2.0
    - monad-memo


