name:                language-grin-jhc
version:             0.8.2.0
github:              "seagull-kamome/jhc"
license:             BSD3
author:              "Hattori, Hiroki"
maintainer:          "seagull.kamome@gmail.com"
copyright:           "Copyright (C) 2018 Hattori, Hiroki. All Rights Reserved."
synopsis:            GRIN languages AST, Parser, PrettyPrinter ...
category:            Language
description:         Please see the README on GitHub at <https://github.com/seagull-kamome/jhc#readme>


library:
  source-dirs: src
  ghc-options:
    - -Wall
  default-extensions:
    - GADTs
    - RankNTypes
    - DataKinds
  dependencies:
    - base >= 4.7 && < 5


